# Generated by Django 4.2.7 on 2023-11-21 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dt_inicio', models.DateTimeField(blank=True, null=True)),
                ('dt_fim', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('valor_acumulado', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'jogo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Loterica',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=255, null=True)),
                ('saldo', models.FloatField(blank=True, null=True)),
                ('telefone', models.CharField(blank=True, max_length=255, null=True)),
                ('cnpj', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Lotérica',
                'db_table': 'loterica',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=255, null=True)),
                ('telefone', models.CharField(blank=True, max_length=255, null=True)),
                ('num_cadastro', models.CharField(max_length=30, verbose_name='Número de Cadastro')),
                ('loterica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='loterica.loterica', verbose_name='Lotérica')),
            ],
            options={
                'verbose_name': 'Funcionário',
                'db_table': 'funcionario',
                'managed': True,
            },
        ),
    ]
