# Generated by Django 4.2.7 on 2023-11-25 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loterica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aposta',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('data', models.DateTimeField(blank=True, null=True)),
                ('numeros', models.JSONField(blank=True, null=True)),
                ('premio', models.FloatField(blank=True, null=True)),
                ('tipo', models.CharField(blank=True, max_length=255, null=True)),
                ('valor', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'aposta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('data', models.DateTimeField(blank=True, null=True)),
                ('numeros', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'resultado',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='num_cadastro',
            field=models.CharField(max_length=30, unique=True, verbose_name='Número de Cadastro'),
        ),
    ]
