# Generated by Django 4.2.7 on 2023-11-16 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loterica', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
