# Generated by Django 4.2.7 on 2023-11-16 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loterica', '0002_alter_funcionario_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='funcionario',
            options={'managed': True, 'verbose_name': 'Funcionário'},
        ),
        migrations.AlterModelOptions(
            name='loterica',
            options={'managed': False, 'verbose_name': 'Lotérica'},
        ),
    ]
