# Generated by Django 4.2.7 on 2023-11-16 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loterica', '0003_alter_funcionario_options_alter_loterica_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='num_cadastro',
            field=models.CharField(max_length=30, verbose_name='Número de Cadastro'),
        ),
    ]
