# Generated by Django 4.2.7 on 2023-11-16 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loterica', '0005_funcionario_id_loterica'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcionario',
            old_name='id_loterica',
            new_name='loterica',
        ),
    ]
