// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameApostador = "apostador"

// Apostador mapped from table <apostador>
type Apostador struct {
	ID         int64   `gorm:"column:id;primaryKey" json:"id"`
	Nome       string  `gorm:"column:nome" json:"nome"`
	Saldo      float64 `gorm:"column:saldo" json:"saldo"`
	Cpf        string  `gorm:"column:cpf" json:"cpf"`
	Depositado float64 `gorm:"column:depositado" json:"depositado"`
	Divida     float64 `gorm:"column:divida" json:"divida"`
	Email      string  `gorm:"column:email" json:"email"`
	Limite     float64 `gorm:"column:limite" json:"limite"`
	Password   string  `gorm:"column:password" json:"password"`
	Username   string  `gorm:"column:username" json:"username"`
}

// TableName Apostador's table name
func (*Apostador) TableName() string {
	return TableNameApostador
}
