// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameBicho = "bicho"

// Bicho mapped from table <bicho>
type Bicho struct {
	ID      int64  `gorm:"column:id;primaryKey" json:"id"`
	Nome    string `gorm:"column:nome;not null" json:"nome"`
	Numeros string `gorm:"column:numeros" json:"numeros"`
}

// TableName Bicho's table name
func (*Bicho) TableName() string {
	return TableNameBicho
}
