// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameJogo = "jogo"

// Jogo mapped from table <jogo>
type Jogo struct {
	ID         int64     `gorm:"column:id;primaryKey" json:"id"`
	DtFim      time.Time `gorm:"column:dt_fim" json:"dt_fim"`
	DtInicio   time.Time `gorm:"column:dt_inicio" json:"dt_inicio"`
	Status     string    `gorm:"column:status" json:"status"`
	LotericaID int64     `gorm:"column:loterica_id" json:"loterica_id"`
}

// TableName Jogo's table name
func (*Jogo) TableName() string {
	return TableNameJogo
}
