export {Bicho} from './Bicho.tsx'
export {Carreira} from './Carreira.tsx'
export {Dependencia} from './Dependencia.tsx'
export {Duvidas} from './Duvidas.tsx'
export {Numero} from './Numero.tsx'
export {Politica} from './Politica.tsx'
export {Servico} from './Servico.tsx'
export {Veganos} from './Veganos.tsx'