name: Go Lint

on:
  push:
    paths:
      - "go-scheduler/**.go"
  pull_request:
    paths:
      - "go-scheduler/**.go"

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: List go-scheduler directory
        run: ls -l go-scheduler

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('go-scheduler/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Instalar Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Instalar golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          working-directory: go-scheduler

      - name: Rodar golangci-lint
        run: golangci-lint run ./...
        working-directory: go-scheduler
