name: Go Lint

on:
  push:
    paths:
      - "bichobet/go-scheduler/**.go"
  pull_request:
    paths:
      - "bichobet/go-scheduler/**.go"

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Instalar golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest

      - name: Rodar golangci-lint
        run: |
          cd go-scheduler
          golangci-lint run ./...
